pipeline {
    agent {
        docker {
            image 'node:16.13.1-alpine'
            alwaysPull false
            reuseNode true
        }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
}
